/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ActivitiesSlugRouteImport } from './routes/activities.$slug'
import { Route as ApiTelemetryRouteImport } from './routes/api/telemetry'
import { Route as CertificationsSlugRouteImport } from './routes/certifications.$slug'
import { Route as ExperienceSlugRouteImport } from './routes/experience.$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesSlugRoute = ActivitiesSlugRouteImport.update({
  id: '/activities/$slug',
  path: '/activities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetryRoute = ApiTelemetryRouteImport.update({
  id: '/api/telemetry',
  path: '/api/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsSlugRoute = CertificationsSlugRouteImport.update({
  id: '/certifications/$slug',
  path: '/certifications/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceSlugRoute = ExperienceSlugRouteImport.update({
  id: '/experience/$slug',
  path: '/experience/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/certifications/$slug': typeof CertificationsSlugRoute
  '/experience/$slug': typeof ExperienceSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/certifications/$slug': typeof CertificationsSlugRoute
  '/experience/$slug': typeof ExperienceSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/certifications/$slug': typeof CertificationsSlugRoute
  '/experience/$slug': typeof ExperienceSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/activities/$slug'
    | '/api/telemetry'
    | '/certifications/$slug'
    | '/experience/$slug'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/activities/$slug'
    | '/api/telemetry'
    | '/certifications/$slug'
    | '/experience/$slug'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/activities/$slug'
    | '/api/telemetry'
    | '/certifications/$slug'
    | '/experience/$slug'
    | '/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ActivitiesSlugRoute: typeof ActivitiesSlugRoute
  ApiTelemetryRoute: typeof ApiTelemetryRoute
  CertificationsSlugRoute: typeof CertificationsSlugRoute
  ExperienceSlugRoute: typeof ExperienceSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$slug': {
      id: '/activities/$slug'
      path: '/activities/$slug'
      fullPath: '/activities/$slug'
      preLoaderRoute: typeof ActivitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry': {
      id: '/api/telemetry'
      path: '/api/telemetry'
      fullPath: '/api/telemetry'
      preLoaderRoute: typeof ApiTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications/$slug': {
      id: '/certifications/$slug'
      path: '/certifications/$slug'
      fullPath: '/certifications/$slug'
      preLoaderRoute: typeof CertificationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/$slug': {
      id: '/experience/$slug'
      path: '/experience/$slug'
      fullPath: '/experience/$slug'
      preLoaderRoute: typeof ExperienceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ActivitiesSlugRoute: ActivitiesSlugRoute,
  ApiTelemetryRoute: ApiTelemetryRoute,
  CertificationsSlugRoute: CertificationsSlugRoute,
  ExperienceSlugRoute: ExperienceSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
