import type { AdminDashboardData } from "./types";

export const INITIAL_ADMIN_DATA: AdminDashboardData = {
  stats: {
    totalViews: 4892,
    uniqueVisitors: 1420,
    avgDwellSeconds: 154,
    resumeDownloads: 198,
    targetCompanyVisits: 47,
    viewsTrendPercent: 24.6,
    visitorsTrendPercent: 18.2,
  },
  trafficSeries: [
    { date: "Sep 18", views: 420, visitors: 110, resumeDownloads: 14 },
    { date: "Sep 19", views: 560, visitors: 145, resumeDownloads: 22 },
    { date: "Sep 20", views: 680, visitors: 190, resumeDownloads: 28 },
    { date: "Sep 21", views: 810, visitors: 240, resumeDownloads: 35 },
    { date: "Sep 22", views: 950, visitors: 285, resumeDownloads: 41 },
    { date: "Sep 23", views: 1120, visitors: 320, resumeDownloads: 52 },
    { date: "Sep 24", views: 1352, visitors: 380, resumeDownloads: 58 },
  ],
  topPages: [
    { path: "/", name: "Portfolio Overview (Hero & Arsenal)", views: 3240, avgDwell: 165 },
    {
      path: "/projects/agentic-supermarket-pos",
      name: "Agentic Supermarket POS",
      views: 940,
      avgDwell: 210,
    },
    {
      path: "/projects/enterprise-ai-recruitment-proctoring",
      name: "Enterprise AI Recruitment",
      views: 760,
      avgDwell: 185,
    },
    {
      path: "/experience/nxtlogic-ai-ml-intern",
      name: "Nxtlogic AI/ML Intern Case Study",
      views: 680,
      avgDwell: 140,
    },
    {
      path: "/projects/multi-agent-equity-research",
      name: "Multi-Agent Equity Research",
      views: 520,
      avgDwell: 195,
    },
    {
      path: "/certifications/freecodecamp-python",
      name: "Python Certification",
      views: 310,
      avgDwell: 95,
    },
  ],
  deviceBreakdown: [
    { name: "Desktop", value: 68 },
    { name: "Mobile", value: 27 },
    { name: "Tablet", value: 4 },
    { name: "Bot", value: 1 },
  ],
  geoBreakdown: [
    { country: "India", code: "IN", city: "Bengaluru", visits: 680, percent: 47.8 },
    { country: "United States", code: "US", city: "Mountain View, CA", visits: 240, percent: 16.9 },
    { country: "India", code: "IN", city: "Coimbatore", visits: 190, percent: 13.3 },
    { country: "United States", code: "US", city: "Seattle, WA", visits: 115, percent: 8.1 },
    { country: "Germany", code: "DE", city: "Berlin", visits: 64, percent: 4.5 },
    { country: "United Kingdom", code: "GB", city: "London", visits: 52, percent: 3.6 },
    { country: "Singapore", code: "SG", city: "Singapore", visits: 41, percent: 2.8 },
  ],
  visitors: [
    {
      id: "v-01",
      sessionToken: "sess_google_mtv_982",
      ip: "172.253.115.1",
      countryCode: "US",
      countryName: "United States",
      city: "Mountain View",
      region: "California",
      asnNumber: "15169",
      asnOrg: "Google LLC",
      isTargetCompany: true,
      deviceType: "desktop",
      os: "macOS 15.0",
      browser: "Chrome 129",
      gpuRenderer: "Apple M3 Max",
      screenWidth: 1728,
      screenHeight: 1117,
      referrer: "https://www.linkedin.com/feed/",
      utmSource: "linkedin",
      utmCampaign: "ai_portfolio",
      activeDwellSeconds: 245,
      maxScrollPercentage: 100,
      hasResumeDownload: true,
      hasContactIntent: true,
      timestamp: "12 mins ago",
      eventsCount: 16,
      timeline: [
        {
          time: "00:00",
          event: "Landed on Portfolio",
          detail: "Referrer: LinkedIn (Recruiter Campaign)",
        },
        {
          time: "00:22",
          event: "Read Experience",
          detail: "Nxtlogic AI/ML Intern & SHAP Explainability (35s dwell)",
        },
        {
          time: "01:05",
          event: "Deep-Dive Project",
          detail: "Agentic Supermarket POS & LangGraph Architecture (68s dwell)",
        },
        {
          time: "02:18",
          event: "Deep-Dive Project",
          detail: "Enterprise AI Recruitment Proctoring (40s dwell)",
        },
        { time: "03:12", event: "Downloaded Resume", detail: "Darshan_R_Resume.pdf (HTTP 200)" },
        { time: "03:45", event: "Copied Contact Email", detail: "darshanr2005@gmail.com" },
      ],
    },
    {
      id: "v-02",
      sessionToken: "sess_msft_rdm_411",
      ip: "20.198.118.42",
      countryCode: "US",
      countryName: "United States",
      city: "Redmond",
      region: "Washington",
      asnNumber: "8075",
      asnOrg: "Microsoft Corporation",
      isTargetCompany: true,
      deviceType: "desktop",
      os: "Windows 11",
      browser: "Edge 128",
      gpuRenderer: "NVIDIA GeForce RTX 4080",
      screenWidth: 2560,
      screenHeight: 1440,
      referrer: "https://github.com/darshan-com",
      utmSource: "github",
      activeDwellSeconds: 198,
      maxScrollPercentage: 90,
      hasResumeDownload: true,
      hasContactIntent: false,
      timestamp: "28 mins ago",
      eventsCount: 12,
      timeline: [
        { time: "00:00", event: "Landed from GitHub", detail: "Profile link click" },
        {
          time: "00:30",
          event: "Inspected Arsenal",
          detail: "Skills Matrix: LangChain, CrewAI, ChromaDB",
        },
        {
          time: "01:15",
          event: "Explored Project",
          detail: "Multi-Agent Equity Research (52s dwell)",
        },
        { time: "02:45", event: "Downloaded Resume", detail: "Darshan_R_Resume.pdf" },
      ],
    },
    {
      id: "v-03",
      sessionToken: "sess_bengaluru_tech_104",
      ip: "103.21.244.15",
      countryCode: "IN",
      countryName: "India",
      city: "Bengaluru",
      region: "Karnataka",
      asnNumber: "55836",
      asnOrg: "Jio Fiber / Tech Hub",
      isTargetCompany: false,
      deviceType: "desktop",
      os: "macOS 14.5",
      browser: "Chrome 128",
      gpuRenderer: "Apple M2 Pro",
      screenWidth: 1920,
      screenHeight: 1080,
      referrer: "Direct Navigation",
      activeDwellSeconds: 162,
      maxScrollPercentage: 100,
      hasResumeDownload: true,
      hasContactIntent: true,
      timestamp: "45 mins ago",
      eventsCount: 14,
      timeline: [
        { time: "00:00", event: "Direct Visit", detail: "Direct address bar entry" },
        { time: "00:40", event: "Read VisionCorp Work", detail: "UI/UX System Design" },
        { time: "01:30", event: "Reviewed Projects", detail: "Robust Vision Pipeline" },
        { time: "02:20", event: "Downloaded Resume", detail: "Darshan_R_Resume.pdf" },
      ],
    },
    {
      id: "v-04",
      sessionToken: "sess_amzn_sea_729",
      ip: "54.240.198.3",
      countryCode: "US",
      countryName: "United States",
      city: "Seattle",
      region: "Washington",
      asnNumber: "16509",
      asnOrg: "Amazon.com Inc",
      isTargetCompany: true,
      deviceType: "desktop",
      os: "macOS 14.4",
      browser: "Firefox 130",
      gpuRenderer: "Apple M1",
      screenWidth: 1440,
      screenHeight: 900,
      referrer: "https://www.linkedin.com/",
      activeDwellSeconds: 210,
      maxScrollPercentage: 85,
      hasResumeDownload: true,
      hasContactIntent: false,
      timestamp: "1 hour ago",
      eventsCount: 11,
      timeline: [
        { time: "00:00", event: "LinkedIn Outbound", detail: "Profile link" },
        { time: "00:45", event: "Read Nxtlogic Experience", detail: "Machine Learning workflow" },
        { time: "01:40", event: "Downloaded Resume", detail: "Darshan_R_Resume.pdf" },
      ],
    },
    {
      id: "v-05",
      sessionToken: "sess_coimbatore_srec_512",
      ip: "157.48.22.9",
      countryCode: "IN",
      countryName: "India",
      city: "Coimbatore",
      region: "Tamil Nadu",
      asnNumber: "45820",
      asnOrg: "ACT Fibernet",
      isTargetCompany: false,
      deviceType: "mobile",
      os: "iOS 18.0",
      browser: "Mobile Safari",
      gpuRenderer: "Apple A17 Pro GPU",
      screenWidth: 393,
      screenHeight: 852,
      referrer: "https://www.instagram.com/",
      activeDwellSeconds: 88,
      maxScrollPercentage: 75,
      hasResumeDownload: false,
      hasContactIntent: false,
      timestamp: "2 hours ago",
      eventsCount: 8,
      timeline: [
        { time: "00:00", event: "Mobile Social Visit", detail: "Instagram bio link" },
        { time: "00:30", event: "BootLoader Sequence", detail: "Completed in 1.4s" },
        { time: "01:10", event: "Browsed Skills", detail: "AI Tools & APIs category" },
      ],
    },
  ],
  inquiries: [
    {
      id: "inq-101",
      name: "Marcus Vance",
      email: "m.vance@techrecruitment.ai",
      company: "Apex AI Staffing (Partnering with Tier-1 AI Lab)",
      roleType: "Lead Technical Recruiter",
      opportunityType: "Full-Time Role",
      message:
        "Hi Darshan, your work on the Agentic Supermarket POS and LangGraph multi-agent systems caught our attention. We are hiring an AI/ML Engineer to build enterprise autonomous agent workflows. Would you be open for a quick 15-minute chat this week?",
      pipelineStage: "new",
      priority: "urgent",
      sentiment: "urgent",
      aiSummary: "High-Priority Recruiter Lead for Full-Time Autonomous Agent / ML Engineer role.",
      createdAt: "Today at 02:45 PM",
    },
    {
      id: "inq-102",
      name: "Sarah Lin",
      email: "sarah.lin@horizonedge.io",
      company: "Horizon Edge Robotics",
      roleType: "Engineering Director",
      opportunityType: "Contract / Project",
      message:
        "Hello Darshan, impressed by your real-time computer vision and anomaly detection pipeline. We are looking for an ML consultant to optimize edge deployment models on NVIDIA Jetson devices.",
      pipelineStage: "screening",
      priority: "high",
      sentiment: "positive",
      aiSummary: "Edge AI / Computer Vision consulting opportunity on Jetson hardware.",
      createdAt: "Yesterday at 11:20 AM",
    },
    {
      id: "inq-103",
      name: "Arun Kumar",
      email: "arun.k@bengalurustartup.co",
      company: "NxtGen Fintech",
      roleType: "Founder & CTO",
      opportunityType: "Full-Time Role",
      message:
        "Loved your NIFTY 50 multi-agent research demo. We are building an algorithmic research copilot and would love to interview you for our founding engineering cohort.",
      pipelineStage: "interview",
      priority: "high",
      sentiment: "positive",
      aiSummary: "Fintech Founder interview invitation for Algorithmic Research AI.",
      createdAt: "2 days ago",
    },
  ],
};
